In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 1.11)

array([1.11, 1.11, 1.11, 1.11, 1.11, 1.11, 1.11, 1.11, 1.11, 1.11])

In [6]:
a = np.array([[1, 2, 3], [10, 11, 20]])

In [8]:
print(a[1])
print(a[1, 2])

[10 11 20]
20


In [10]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [11]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [14]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([[1, 2], [3, 4], [5, 6]])

In [20]:
n[:, 1] = [10, 20, 30]
print(n)

[[ 1 10]
 [ 3 20]
 [ 5 30]]


In [24]:
np.random.rand(3, 2) # uniform distro

array([[0.10038358, 0.20181909],
       [0.63731567, 0.81951954],
       [0.6129746 , 0.90118122]])

In [22]:
np.random.randn(3, 2) # normal distro

array([[-0.95799463,  0.83621754],
       [ 0.76357791,  1.25131134],
       [ 0.68724409, -3.382318  ]])

In [27]:
np.random.seed(1)
np.random.rand(3, 2) # pseudoramdom

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02]])

In [29]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [30]:
a + 100

array([100, 101, 102, 103, 104])

In [31]:
a < 3

array([ True,  True,  True, False, False])

In [32]:
(a < 3).dtype

dtype('bool')

In [33]:
a[a < 3]

array([0, 1, 2])

In [34]:
a.min()

np.int64(0)

In [35]:
a.max()

np.int64(4)

In [36]:
a.sum()

np.int64(10)

In [37]:
a.mean()

np.float64(2.0)

In [38]:
a.std()

np.float64(1.4142135623730951)

In [39]:
n = np.random.randn(3, 2)

In [40]:
n.mean()

np.float64(-0.34227776310897556)

In [41]:
n.mean(axis=0) # columnwise

array([ 0.69401588, -1.37857141])